/**
 * VitePress docs generator — template from the vitepress-cursor-docs skill.
 * Copy to docs/scripts/generate-docs.mjs. Set GITHUB_BASE (GitHub blob URL prefix for
 * "Auto-generated from" links), e.g. https://github.com/<owner>/<repo>/blob/HEAD/
 */

import { promises as fs } from "fs";
import path from "path";

// --- Paths ---
const cwd = process.cwd();
const inDocs = path.basename(cwd) === "docs";
const repoRoot = inDocs ? path.resolve(cwd, "..") : cwd;
const docsRoot = inDocs ? cwd : path.join(repoRoot, "docs");
const contentRoot = path.join(docsRoot, "src");

const PATHS = {
  cursorRules: {
    in: path.join(repoRoot, ".cursor", "rules"),
    out: path.join(contentRoot, "cursor-rules"),
  },
  agentSkills: {
    in: path.join(repoRoot, ".cursor", "skills"),
    out: path.join(contentRoot, "agent-skills"),
  },
  cursorCommands: {
    in: path.join(repoRoot, ".cursor", "commands"),
    out: path.join(contentRoot, "cursor-commands"),
  },
};

/** Flat sections: one output dir per source dir, one doc per file (rules + commands). */
const FLAT_SECTIONS = [
  {
    pathKey: "cursorRules",
    ext: ".mdc",
    sectionTitle: "Cursor rules",
    sidebarBase: "/cursor-rules/",
  },
  {
    pathKey: "cursorCommands",
    ext: ".md",
    sectionTitle: "Cursor commands",
    sidebarBase: "/cursor-commands/",
  },
];

// Required: set to your repository (GitHub blob URL prefix).
const GITHUB_BASE = "https://github.com/OWNER/REPO/blob/HEAD/";

// --- FS ---
async function ensureDir(dir) {
  await fs.mkdir(dir, { recursive: true });
}

async function pathExists(p) {
  try {
    await fs.stat(p);
    return true;
  } catch {
    return false;
  }
}

// --- Content (Markdown) ---
function stripFrontmatter(content) {
  if (!content.startsWith("---")) return content;
  const lines = content.split("\n");
  const end = lines.findIndex((line, i) => i > 0 && line.trim() === "---");
  if (end === -1) return content;
  return lines
    .slice(end + 1)
    .join("\n")
    .replace(/^\s*\n/u, "");
}

function getFirstHeading(content) {
  const m = content.match(/^#+\s+(.+)$/mu);
  return m ? m[1].trim() : null;
}

/** Rewrite repo paths .cursor/skills/... to VitePress routes /agent-skills/... (extensionless). */
function rewriteRepoLinksToDocs(content) {
  return content.replace(
    /\]\((\.\/)?\.cursor\/skills\/([^)]+)\)/gu,
    (_, _lead, segment) => {
      const pathNoExt = segment.replace(/\.md$/iu, "");
      return `](/agent-skills/${pathNoExt})`;
    },
  );
}

function withAutoGeneratedHeader(content, relSource) {
  const link = `${GITHUB_BASE}${relSource.replace(/\\/gu, "/")}`;
  const block = `> Auto-generated from [\`${relSource}\`](${link}).`;
  const cleaned = stripFrontmatter(content);
  const lines = cleaned.split("\n");
  const i = lines.findIndex((l) => /^#+\s/u.test(l));
  if (i === -1) return rewriteRepoLinksToDocs(`${block}\n\n${cleaned}`);
  let j = i + 1;
  while (j < lines.length && lines[j].trim() === "") j += 1;
  const titleBlock = lines.slice(0, j).join("\n");
  const rest = lines.slice(j).join("\n");
  const out = rest
    ? `${titleBlock}\n${block}\n\n${rest}`
    : `${titleBlock}\n${block}`;
  return rewriteRepoLinksToDocs(out);
}

async function writeDocFile(destPath, rawContent, relSource) {
  await ensureDir(path.dirname(destPath));
  await fs.writeFile(
    destPath,
    withAutoGeneratedHeader(rawContent, relSource),
    "utf8",
  );
}

// --- Index page ---
function buildIndexPage(title, items) {
  const header = [`# ${title}`, ""];
  const tableHeader = "| Title | Source |";
  const tableSep = "| --- | --- |";
  const rows = items.map((i) => {
    const linkText = i.title ?? i.name;
    const fileLink = i.file.endsWith("index.md")
      ? i.file.replace(/\/index\.md$/u, "/")
      : i.file;
    const githubLink = `${GITHUB_BASE}${i.source.replace(/\\/gu, "/")}`;
    return `| [${linkText}](./${fileLink}) | [\`${i.source}\`](${githubLink}) |`;
  });
  return [...header, tableHeader, tableSep, ...rows, ""].join("\n");
}

async function writeSectionIndex(outDir, title, items) {
  items.sort((a, b) => a.name.localeCompare(b.name));
  await fs.writeFile(
    path.join(outDir, "index.md"),
    buildIndexPage(title, items),
    "utf8",
  );
}

// --- Sidebar ---
function buildSectionSidebar(base, sectionTitle, items) {
  return {
    [base]: [
      { text: sectionTitle, link: base },
      ...items.map((i) => ({
        text: i.title ?? i.name,
        link: `${base}${i.name}`,
      })),
    ],
  };
}

async function buildAgentSkillsSidebar(outDir, indexItems) {
  const base = "/agent-skills/";
  const items = [{ text: "Agent skills", link: base }];

  for (const skill of indexItems) {
    const refDir = path.join(outDir, skill.name, "references");
    const entry = {
      text: skill.title ?? skill.name,
      link: `${base}${skill.name}/`,
    };

    if (await pathExists(refDir)) {
      const stat = await fs.stat(refDir);
      if (stat.isDirectory()) {
        const refs = await fs.readdir(refDir, { withFileTypes: true });
        const mdFiles = refs.filter(
          (e) => e.isFile() && e.name.endsWith(".md"),
        );
        const mdRefs = await Promise.all(
          mdFiles.map(async (e) => {
            const filePath = path.join(refDir, e.name);
            const content = await fs.readFile(filePath, "utf8");
            const title =
              getFirstHeading(stripFrontmatter(content)) ??
              e.name.replace(/\.md$/u, "");
            return {
              text: title,
              link: `${base}${skill.name}/references/${e.name.replace(/\.md$/u, "")}`,
            };
          }),
        );
        mdRefs.sort((a, b) => a.text.localeCompare(b.text));
        if (mdRefs.length > 0) {
          entry.collapsed = true;
          entry.items = mdRefs;
        }
      }
    }
    items.push(entry);
  }

  return { [base]: items };
}

// --- Generators ---
async function generateFlatSection({ pathKey, ext, sectionTitle }) {
  const { in: srcDir, out: outDir } = PATHS[pathKey];
  if (!(await pathExists(srcDir))) return [];

  await ensureDir(outDir);
  const items = [];

  for (const entry of await fs.readdir(srcDir, { withFileTypes: true })) {
    if (!entry.isFile() || !entry.name.endsWith(ext)) continue;

    const srcPath = path.join(srcDir, entry.name);
    const name = entry.name.slice(0, -ext.length);
    const relSource = path.relative(repoRoot, srcPath);
    const destPath = path.join(outDir, `${name}.md`);

    const raw = await fs.readFile(srcPath, "utf8");
    await writeDocFile(destPath, raw, relSource);

    items.push({
      name,
      file: `${name}.md`,
      source: relSource,
      title: getFirstHeading(stripFrontmatter(raw)) ?? name,
    });
  }

  await writeSectionIndex(outDir, sectionTitle, items);
  return items;
}

async function generateAgentSkills() {
  const { in: srcDir, out: outDir } = PATHS.agentSkills;
  if (!(await pathExists(srcDir))) return null;

  await ensureDir(outDir);
  const indexItems = [];
  const stack = [{ src: srcDir, dest: outDir }];

  while (stack.length > 0) {
    const { src, dest } = stack.pop();
    await ensureDir(dest);

    for (const entry of await fs.readdir(src, { withFileTypes: true })) {
      const srcPath = path.join(src, entry.name);
      const isSkill = entry.name === "SKILL.md";
      const destName = isSkill ? "index.md" : entry.name;
      const destPath = path.join(dest, destName);

      if (entry.isDirectory()) {
        stack.push({ src: srcPath, dest: destPath });
        continue;
      }
      if (!entry.isFile()) continue;

      const relSource = path.relative(repoRoot, srcPath);
      const raw = await fs.readFile(srcPath, "utf8");
      await writeDocFile(destPath, raw, relSource);

      if (isSkill) {
        const skillName = path.basename(path.dirname(srcPath));
        indexItems.push({
          name: skillName,
          file: path.relative(outDir, destPath).replace(/\\/gu, "/"),
          source: relSource,
          title: getFirstHeading(stripFrontmatter(raw)) ?? skillName,
        });
      }
    }
  }

  await writeSectionIndex(outDir, "Agent skills", indexItems);
  return buildAgentSkillsSidebar(outDir, indexItems);
}

// --- Main ---
async function main() {
  await ensureDir(docsRoot);
  await ensureDir(contentRoot);

  const [agentSkillsSidebar, ...flatSectionItems] = await Promise.all([
    generateAgentSkills(),
    ...FLAT_SECTIONS.map((s) => generateFlatSection(s)),
  ]);

  const sidebar = {
    ...(agentSkillsSidebar ?? {}),
    ...Object.assign(
      {},
      ...FLAT_SECTIONS.map((s, i) =>
        buildSectionSidebar(
          s.sidebarBase,
          s.sectionTitle,
          flatSectionItems[i] ?? [],
        ),
      ),
    ),
  };

  const vitepressDir = path.join(docsRoot, ".vitepress");
  await ensureDir(vitepressDir);
  await fs.writeFile(
    path.join(vitepressDir, "sidebar.generated.mts"),
    `// Auto-generated by scripts/generate-docs.mjs\nexport default ${JSON.stringify(sidebar, null, 2)};\n`,
    "utf8",
  );
}

main().catch((err) => {
  console.error("Failed to generate docs:", err);
  process.exitCode = 1;
});
